import { FamilyMember } from './family-tree.model';

export const FAMILY_DATA: FamilyMember[] = [
  {
    id: 'henri',
    firstName: 'Henri',
    lastName: 'Dupont',
    birthYear: 1935,
    deathYear: 2010,
    gender: 'male',
    profession: 'Ingénieur civil',
    city: 'Lyon',
    spouseId: 'marguerite',
    parentIds: [],
  },
  {
    id: 'marguerite',
    firstName: 'Marguerite',
    lastName: 'Bon',
    birthYear: 1938,
    gender: 'female',
    profession: 'Institutrice',
    city: 'Lyon',
    spouseId: 'henri',
    parentIds: [],
  },
  {
    id: 'pierre',
    firstName: 'Pierre',
    lastName: 'Dupont',
    birthYear: 1962,
    gender: 'male',
    profession: 'Médecin généraliste',
    city: 'Grenoble',
    spouseId: 'sylvie',
    parentIds: ['henri', 'marguerite'],
  },
  {
    id: 'sylvie',
    firstName: 'Sylvie',
    lastName: 'Martin',
    birthYear: 1964,
    gender: 'female',
    profession: 'Architecte',
    city: 'Grenoble',
    spouseId: 'pierre',
    parentIds: [],
  },
  {
    id: 'claire',
    firstName: 'Claire',
    lastName: 'Dupont',
    birthYear: 1965,
    gender: 'female',
    profession: 'Avocate',
    city: 'Paris',
    parentIds: ['henri', 'marguerite'],
  },
  {
    id: 'marc',
    firstName: 'Marc',
    lastName: 'Dupont',
    birthYear: 1968,
    gender: 'male',
    profession: 'Chef cuisinier',
    city: 'Bordeaux',
    spouseId: 'isabelle',
    parentIds: ['henri', 'marguerite'],
  },
  {
    id: 'isabelle',
    firstName: 'Isabelle',
    lastName: 'Leroy',
    birthYear: 1970,
    gender: 'female',
    profession: 'Infirmière',
    city: 'Bordeaux',
    spouseId: 'marc',
    parentIds: [],
  },
  {
    id: 'lucas',
    firstName: 'Lucas',
    lastName: 'Dupont',
    birthYear: 1992,
    gender: 'male',
    profession: 'Développeur web',
    city: 'Lyon',
    parentIds: ['pierre', 'sylvie'],
  },
  {
    id: 'emma',
    firstName: 'Emma',
    lastName: 'Dupont',
    birthYear: 1995,
    gender: 'female',
    profession: 'Étudiante en médecine',
    city: 'Paris',
    parentIds: ['pierre', 'sylvie'],
  },
  {
    id: 'leo',
    firstName: 'Léo',
    lastName: 'Dupont',
    birthYear: 1999,
    gender: 'male',
    profession: 'Lycéen',
    city: 'Bordeaux',
    parentIds: ['marc', 'isabelle'],
  },
  {
    id: 'jade',
    firstName: 'Jade',
    lastName: 'Dupont',
    birthYear: 2002,
    gender: 'female',
    profession: 'Collégienne',
    city: 'Bordeaux',
    parentIds: ['marc', 'isabelle'],
  },
];
